server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://team10-instance-rds.cq1xmq6wnfs8.us-east-1.rds.amazonaws.com:3306/team10_db
    username: admin
    password: admin123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  accessKeyId: AKIAV5BXM55AVMWRXSHW
  secretAccessKey: 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